name: Swift

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Bundle Install
      run: |
        bundle install
    - name: Run TestCase
      run: |
        bundle exec fastlane run_test
